services:
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile-php
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
      - ./html:/var/www/html/html # Per servire anche i file HTML/CSS/JS dal container PHP
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data:
